%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: W:\RD\Projects\2025\Logan M\MatLab Bimodal Curve Fitting\TSE001 75 min run 25-5_2025-05-20-14-02-21_TSE001 run 25.xlsx
%    Worksheet: Measurement 5
%
% Auto-generated by MATLAB on 19-May-2025 10:26:32

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet
opts.Sheet = "Measurement 5";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "ParticleDiameter", "Var7", "SizeDistribution1"];
opts.SelectedVariableNames = ["ParticleDiameter", "SizeDistribution1"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "double", "char", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var7"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["ParticleDiameter", "SizeDistribution1"], "TreatAsMissing", '');

% Import the data
tbl = table;
ranges = ["A1:H5", "A7:H147"];
for idx = 1:length(ranges)
    opts.DataRange = ranges(idx);
    tb = readtable("W:\RD\Projects\2025\Logan M\MatLab Bimodal Curve Fitting\TSE001 75 min run 25-5_2025-05-20-14-02-21_TSE001 run 25.xlsx", opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
ParticleDiameter = tbl.ParticleDiameter;
SizeDistribution1 = tbl.SizeDistribution1;

%% Clear temporary variables
clear idx opts ranges tb tbl